[package]
name = "rchat"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[workspace]
members = [
    ".",
    "crates/apple-metal-shim",
    "crates/rchat-audio-processing",
    "crates/rchat-core",
    "crates/rchat-libvpx",
    "crates/rchat-screen-capture",
    "crates/rchat-tui",
    "crates/rchat-video-capture",
    "crates/sonora-aec3",
]
resolver = "2"

[patch.crates-io]
apple-metal = { path = "crates/apple-metal-shim" }
sonora-aec3 = { path = "crates/sonora-aec3" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519

name = "rchat_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]

tauri-build = { version = "2", features = [] }

[profile.dev.package."*"]
debug = 0           # Turn off debug info for all dependencies
opt-level = 3       # Maximize optimization for dependencies (makes app run faster too)

[profile.dev]
debug = 1

[dependencies]

rvault-core = { git = "https://github.com/ata-sesli/rvault", rev = "7dda2de45ac31eccb17dad7d1a4f1ebdd893e99c" }
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rchat-core = { path = "crates/rchat-core" }
libp2p = { version = "0.56.0", features = [
    "tcp", "dns", "noise", "yamux",
    "gossipsub", "mdns", "kad", "identify", "ping",
    "macros", "request-response", "tokio", "cbor", "quic",
    "relay", "dcutr"
] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
tokio = { version = "1.48.0", features = [
    "rt-multi-thread", "macros", "net", "time", "sync", "io-util"
] }
base64 = "0.22.1"
octocrab = "0.48.1"
flate2 = { version = "1.1.5", features = ["zlib"] }
rand = "0.8.5"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
tauri-plugin-deep-link = "2"
rchat-screen-capture = { path = "crates/rchat-screen-capture" }
rchat-video-capture = { path = "crates/rchat-video-capture" }
[dev-dependencies]
tempfile = "3.23.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = "2"
