[package]
name = "rchat-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rchat_core"

[dependencies]
rvault-core = { git = "https://github.com/ata-sesli/rvault", rev = "7dda2de45ac31eccb17dad7d1a4f1ebdd893e99c" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
libp2p = { version = "0.56.0", features = [
    "tcp", "dns", "noise", "yamux",
    "gossipsub", "mdns", "kad", "identify", "ping",
    "macros", "request-response", "tokio", "cbor", "quic",
    "relay", "dcutr"
] }
futures = "0.3.31"
rusqlite = { version = "0.31.0", features = ["bundled"] }
ed25519-dalek = { version = "2.2.0", features = ["rand_core"] }
tokio = { version = "1.48.0", features = [
    "rt-multi-thread", "macros", "net", "time", "sync", "io-util", "fs"
] }
fastcdc = "3.2.1"
directories = "6.0.0"
anyhow = "1.0.100"
reqwest = { version = "0.12.24", features = ["json"] }
base64 = "0.22.1"
octocrab = "0.48.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
flate2 = { version = "1.1.5", features = ["zlib"] }
rand = "0.8.5"
sha2 = "0.10.9"
hex = "0.4.3"
hostname = "0.4.2"
local-ip-address = "0.6.8"
zeroconf = "0.17.0"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
zeroize = { version = "1.8.2", features = ["derive"] }
cpal = "0.15.3"
opus = "0.3.1"
rchat-audio-processing = { path = "../rchat-audio-processing" }
rchat-libvpx = { path = "../rchat-libvpx" }
rchat-screen-capture = { path = "../rchat-screen-capture" }
rchat-video-capture = { path = "../rchat-video-capture" }
rubato = { version = "2.0.0", default-features = false }

[dev-dependencies]
tempfile = "3.23.0"
